### ISSUE TITLE
addition example is slow to fail

### ISSUE THREAD

**Issue by jeshan** [triska/clpz#26]
In this Sicstus example,

```prolog
pred(A, B, C) :-
    Max = 10000,
    [A, B] ins 0..Max,
    B #= C+A-Max,
    B #= C+1.
```
The predicate correctly fails since `C+1` does not fit `B`'s `Max` supremum (but `C+0` would fit).
However, it is very slow to terminate (due to `Max` being big).
What can be done to fasten this seemingly simple kind of code? (In practice, these constraints come from more complex predicates that are hard to relate)

**Comment by UWN** [comment]
Also SICStus is slow here but still faster by a factor of 10^5. It shows with larger `Max`. If you can, subtract the two equations from each other yielding a redundant new one without `B` and `C`. Thus `0 #= A-Max-1`.

**Comment by triska** [comment]
Thank you a lot for this example!

I have made it a bit faster with the change filed in https://github.com/mthom/scryer-prolog/pull/2258, could you please try it out?

**Comment by triska** [comment]
> But can we find some other similar scenarios (e.g subtraction and multiplication) **and fix them altogether**?

From just these examples, it is hard to tell what exactly is needed here. For instance, let's take `example2/4` which you posted:

<pre>
example2(A, B, C, D) :-
    Max is 20*1000,
    [A, B, C, D] ins 0..Max,
    D #= C-2,                   % change -2 to -1 to succeed
    D + A #= C,
    A + Max-1 #= B.
</pre>

We note that `D #= C - 2`, and **we can use this information** by syntactically replacing `D` by `C - 2` where it occurs. For instance, we can rewrite the clause to:

<pre>
example2(A, B, C, D) :-
    Max is 20*1000,
    [A, B, C, D] ins 0..Max,
    D #= C-2,                   % change -2 to -1 to succeed
    <b>C - 2</b> + A #= C,
    A + Max-1 #= B.
</pre>

And now we get:

<pre>
<b>?- time(example2(A,B,C,D)).</b>
   % CPU time: 0.002s, 2_199 inferences
   false.
</pre>

So, a simple textual substitution has made the example thousands of times faster. Is there any general point we can deduce from this?

One idea that you could try is to slightly change the code so that the posted constraints are available and can be reasoned about as **Prolog&nbsp;terms**. For instance, consider changing `:-` to `-->` to turn the clause into a DCG:

<pre>
example2(A, B, C, D) --&gt;
    Max is 20*1000,
    [A, B, C, D] ins 0..Max,
    D #= C-2,
    C - 2 + A #= C,
    A + Max-1 #= B.
</pre>

With the following additional definitions:

<pre>
X is Expr --&gt; [X is Expr].
A #= B    --&gt; [A #= B].
Xs ins D  --&gt; [Xs ins D].
</pre>

we get:

<pre>
<b>?- phrase(example2(A,B,C,D), Gs).</b>
   Gs = [_A is 20*1000,[A,B,C,D]ins 0.._A,D#=C-2,C-2+A#=C,A+_A-1#=B].
</pre>

You can now analyze these goals and perform such substitutions automatically.

**Comment by triska** [comment]
Thank you a lot, I greatly appreciate your help with this!

The key task would be to figure out **what exactly is needed here** in the sense that: 

1. It improves the run time of your examples and others like it, and 
2. it does not significantly slow down other examples.
 
There will always be an inherent trade-off between (1) and (2): Just writing code to detect *whether an instance of a CSP has a certain shape* already costs computation&nbsp;time, and therefore negatively impacts all examples that are not of this shape.

From an ideal constraint solver, we expect that all semantically equivalent formulations of a problem are solved with the same (optimal) performance. This seems not attainable in practice, and we already have semantically equivalent constraints with different performance in the same situations, such as `all_different/1` and `all_distinct/1`. Applications can choose which of these they want to use, and such application-specific constraint considerations already occur in practice.

For `example3/5`, I hoped that just **varying the order in which the constraints are posted** can improve performance, and I wrote:

<pre>
X is Expr --&gt; [X is Expr].
A #= B    --&gt; [A #= B].
Xs ins D  --&gt; [Xs ins D].
X = Y     --&gt; [X = Y].

goal_priority(Goal, P) :-
        functor(Goal, F, _),
        functor_priority(F, P).

functor_priority(=   , 0).
functor_priority(is  , 0).
functor_priority(ins , 3).
functor_priority(#=  , 2).
</pre>

This is intended to post the constraints in such a way that propagation is delayed as long as possible, so that *all* constraints can be taken into account when the domains of all variables become restricted to finite sets:

<pre>
?- phrase(example3(A,B,C,D,E), Gs0),
   maplist(goal_priority, Gs0, Ps0),
   pairs_keys_values(Pairs0, Ps0, Gs0),
   keysort(Pairs0, Pairs),
   pairs_values(Pairs, Gs),
   time(maplist(call, Gs)).
</pre>

Unfortunately, it did not help in this case. Maybe a different order yields better results?

**Comment by UWN** [comment]
(Not 100% sure, just thinking) Another possibility could be to have an extra execution mode where constraints are only posted without any propagation. Then, there is a phase were some adding of other constraints and the like happens. And only then, finally they are actually activated. In this manner one does not have to reformulate the problem, but it adds some kind of state.

**Comment by UWN** [comment]
For one, there is [`fd_batch/1`](https://sicstus.sics.se/sicstus/docs/latest4/html/sicstus.html/Posting-Constraints.html) in SICStus. But the limitations there are quite problematic. In fact, since version 4, SICStus has introduced many such anti-nondeterministic improvements which hurts declarative properties a lot.

**Comment by UWN** [comment]
```
ulrich@gupu:/opt/gupu/scryer-prolog$ target/release/scryer-prolog -v
v0.9.3-180-g58cd0d16
ulrich@gupu:/opt/gupu/scryer-prolog$ target/release/scryer-prolog
?- 2*X #= Y-0.
   clpz:(2*X#=Y), clpz:(2*_A#=Y).
?- 2*X #= Y-0,Y=0.
   X = 0, Y = 0.

**Comment by UWN** [comment]
This is the current build with master of Scryer.

And SICStus 4.9.0 is fine too:

```
| ?- use_module(clpz).  
% compiling /opt/gupu/clpz/clpz.pl...
...
% compiled /opt/gupu/clpz/clpz.pl in module clpz, 658 msec 2683760 bytes
yes
| ?- 	2*X #= Y-0.
clpz:(2*_A#=Y),
clpz:(2*X#=Y) ? ;
no
| ?- 2*X #= Y-0,Y=0.
X = 0,
Y = 0 ? ;
no
```
(in general it helps to post separate issues for separate problems. But at least here, I cannot see any)
